name: Reuseable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of the dpeloyment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    #secrets:
    #  some-secret:
    #    required: true
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.step-result.outputs.step-Result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Output Information
        run: echo "Deploying & uploading..."
      - name: Set Result Output
        id: step-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
